/**
 * Filesystem detail for a config author's own `completionItem/resolve` handler.
 *
 * THE SECOND HALF OF THIS PACKAGE, AND THE REASON IT HAS TWO. Work too
 * expensive to do for every item is done for the ONE ITEM THE USER HIGHLIGHTS.
 *
 * THE ARITHMETIC IS THE ARGUMENT. The completion beside this file lists one
 * directory and offers what is in it -- and a directory of a few thousand
 * entries is ordinary. One `stat` per entry to show a size would put a few
 * thousand syscalls on the keystroke that opened the popup; one `stat` per
 * highlighted item puts one syscall on an idle moment. Same information, and the
 * only difference is WHEN it is fetched.
 *
 * IT IS PAIRED WITH THE COMPLETION MODULE AND THE IMPORT BELOW IS THE PAIRING.
 * tsudoi keeps NO record of what a completion handler produced -- it is ruled at
 * the method map tsudoi's own types declare -- so this handler cannot ask tsudoi
 * whether an item is one of this package's own. It can only read what the
 * completion module WROTE ONTO THE ITEM, which is why the mark and its reader
 * are defined THERE and imported here rather than spelled out twice. Two modules
 * agreeing about a key by convention drift the first time either is edited, and
 * nothing in an editor says so: the details simply stop appearing.
 *
 * THAT IMPORT IS WHY THE TWO HALVES SHIP AS ONE PACKAGE. The mark is unpublished
 * on purpose; split across two packages it would have to be published, and every
 * change to how an item is marked would become a compatibility question. And the
 * split could not be undone by a config author either: tsudoi REFUSES a config
 * supplying `completionItem/resolve` with no completion handler beside it, so
 * this handler is unusable without the one beside it.
 *
 * WHAT A MAINTAINER MUST NOT CLOSE, and it is a property of any resolve handler
 * rather than of this one: THE ITEM ARRIVES FROM THE CLIENT.
 * `data` is whatever the client sent back, so a mark can be forged, and this
 * handler will then `stat` a path nobody's completion chose. That is harmless
 * here -- a `stat` reveals a size and a date to the user who asked for it, on a
 * machine they are already running the server on -- and it would NOT be harmless
 * in a handler that opened the file, ran a command, or answered with its
 * contents. Nothing is validated below, deliberately: a check would suggest this
 * boundary can be closed, and it cannot be. What decides it is what the handler
 * DOES with the path.
 */
// `Stats` is declared by node:fs and only the promise-shaped `stat` by
// node:fs/promises, so the two lines are the runtimes' shape rather than a
// preference -- measured, TS2724 names it.
import type { Stats } from "node:fs";
import { readdir, stat } from "node:fs/promises";
import type { MethodHandler } from "@atusy/tsudoi-language-server/types";
import {
  completedPath,
  completedSource,
  documentationFor,
  preferredFormat,
  type DirectoryListing,
} from "./completion.ts";

/**
 * What one line of `detail` says about a path.
 *
 * `detail` AND NOT `documentation`, and it is the counterpart of that module's
 * opposite choice: the documentation is a multi-line block with a rule in it,
 * while this is one line a client can show inline beside the label -- which is
 * where a size and a date want to be read.
 *
 * NO SIZE FOR A DIRECTORY, which is a decision rather than an omission. A
 * directory's `size` is the size of its directory ENTRY -- 64 units on one
 * filesystem and 4096 on the next for the same two children -- so it is the
 * filesystem's business and says nothing about what is inside. Showing it would
 * put a number in front of a user that invites exactly the wrong reading.
 *
 * MTIME AS ISO 8601 IN UTC, because this string is generated by a server and
 * read by a person who may be anywhere: a locale-formatted date would be
 * formatted for the machine the server happens to run on.
 */
function detailFor(stats: Stats): string {
  const modified = `modified ${stats.mtime.toISOString()}`;
  return stats.isDirectory()
    ? `directory · ${modified}`
    : `file · ${String(stats.size)} bytes · ${modified}`;
}

/**
 * A `completionItem/resolve` handler that fills in a path item's file detail.
 *
 * THE ITEM COMES BACK UNCHANGED IN TWO CASES, and neither is an error path.
 *
 * AN ITEM THIS PACKAGE DID NOT PRODUCE carries no mark, and the protocol's
 * answer REPLACES the item in the client's list -- so anything other than the
 * item itself DROPS THE ENTRY THE USER IS LOOKING AT. tsudoi rules it at the same
 * method map, and a client may legitimately send one: resolve asks about an item
 * the client holds, not about one tsudoi remembers.
 *
 * A PATH THAT IS GONE by the time the user highlights the item is ordinary
 * rather than exceptional -- a popup outlives a `git checkout` in another window
 * -- so the rejection is swallowed for the reason an unlistable directory
 * contributes nothing to completion instead of failing it: an escaped rejection
 * is answered -32603 and takes away the popup the user is reading. Nothing is
 * written to stderr either, or every stale item a user scrolls past would put a
 * line in the editor's log.
 *
 * A COPY RATHER THAN A MUTATION, because the item is the request's params and a
 * handler that edits them in place is writing into somebody else's object.
 *
 * THE MULTI-LINE BLOCK IS REBUILT AND NEVER APPENDED TO, FOR EITHER KIND. What
 * comes back is the CLIENT'S text -- as forgeable as the mark, one field over --
 * so an answer built by appending to it would be an answer built out of a string
 * a client can put anything in. Rebuilding depends on nothing the client can
 * mangle: the path is read from disk, the source comes off the mark through a
 * closed set, and the format is re-read from THE SESSION rather than from
 * anything the item carried. A FILE'S BLOCK IS REBUILT TOO, which is why this
 * runs on every path item and not only on directories -- rebuilding for
 * directories alone would leave a file answered with the client's own text --
 * and for a file the rebuild reproduces exactly what the completion wrote.
 */
export const resolvePathStat: MethodHandler<"completionItem/resolve"> = async (context, item) => {
  const path = completedPath(item);
  if (path === undefined) {
    return item;
  }
  try {
    const stats = await stat(path);
    return {
      ...item,
      detail: detailFor(stats),
      documentation: documentationFor(
        path,
        completedSource(item),
        // READ FROM THE SESSION THE HANDLER WAS HANDED, per request, for the
        // reason the completion half reads it per request: the block is composed
        // here, so it is composed for the client that asked for it.
        preferredFormat(
          context.tsudoi.clientCapabilities.textDocument?.completion?.completionItem
            ?.documentationFormat,
        ),
        stats.isDirectory() ? await listingOf(path) : undefined,
      ),
    };
  } catch {
    return item;
  }
};

/**
 * What one directory holds, ready to be rendered.
 *
 * THE WHOLE DIRECTORY IS READ, ON PURPOSE, and the cost was MEASURED rather than
 * feared: one directory of five thousand entries, names only, drains in 51 ms on
 * bun 1.3.13 and 135 ms on deno 2.8.3 (macOS/APFS, mean of 5), against the ~1.1 s
 * of per-entry stats this package exists to refuse and against a completion half
 * that ALREADY drains an entire directory on every keystroke to filter it. A
 * drain once per HIGHLIGHT cannot be the expensive thing here.
 *
 * WHAT DOES NOT SHRINK WITH IT IS THE PAYLOAD -- those five thousand names are
 * eighty-five thousand characters in one response and five thousand lines in one
 * popup -- so the bound this listing is rendered under is on entries SHOWN and
 * never on entries read. THE COST IS LINEAR AND A DIRECTORY IS UNBOUNDED, which
 * is ACCEPTED rather than guarded: the only guard available would bound the read
 * by TIME, and a highlight that answers differently depending on how busy the
 * machine was is a defect of its own. A hundred thousand entries is UNMEASURED.
 *
 * NAMES ONLY, WHICH IS WHY `readdir` RATHER THAN `opendir`: no entry's kind is
 * asked for, so nothing here costs a stat per child -- and nothing iterates a
 * handle this function must remember to release.
 *
 * SORTED BY CODE UNIT AND NEVER BY LOCALE, and the first reason is testability
 * rather than taste: a directory's own order is the filesystem's bookkeeping,
 * promised by nothing, so an unsorted block reads differently on two machines
 * and no whole-value assertion can be written against it at all. `localeCompare`
 * is refused for the reason the ISO date beside it is: this string is built by a
 * server and read by a person who may be anywhere.
 */
async function listingOf(path: string): Promise<DirectoryListing> {
  const names = (await readdir(path)).sort();
  return { names: names.slice(0, entriesShown), total: names.length };
}

/**
 * How many of a directory's entries one answer RENDERS. A judgement value, and
 * the payload is what it is about: five thousand names are eighty-five thousand
 * characters in one response where the first twenty are three hundred, and a
 * popup is read by a person rather than parsed.
 *
 * A BOUND ON THE RENDERING AND NEVER ON THE READ, which is the distinction the
 * whole directory being drained rests on: the answer states how many entries
 * there really are, and it can only do that by having counted them.
 *
 * NOT EXPORTED, AS THE BATCH SIZE BESIDE IT IS NOT: what it decides is visible on
 * the wire -- as the number of names one resolved directory carries -- so a test
 * importing it would agree only with itself.
 */
const entriesShown = 20;
