/**
 * Filesystem detail for a config author's own `completionItem/resolve` handler.
 *
 * WHAT THIS IS AND WHAT IT IS NOT: an EXAMPLE, in examples/, and not a line of
 * it lives in tsudoi. It is here to show WHAT THE METHOD IS FOR, which is the
 * one thing a list of supported methods cannot: work too expensive to do for
 * every item is done for the ONE ITEM THE USER HIGHLIGHTS.
 *
 * THE ARITHMETIC IS THE ARGUMENT. `examples/completion-path.ts` lists one
 * directory and offers what is in it -- and a directory of a few thousand
 * entries is ordinary. One `stat` per entry to show a size would put a few
 * thousand syscalls on the keystroke that opened the popup; one `stat` per
 * highlighted item puts one syscall on an idle moment. Same information, and the
 * only difference is WHEN it is fetched.
 *
 * IT IS PAIRED WITH THE COMPLETION MODULE AND THE IMPORT BELOW IS THE PAIRING.
 * tsudoi keeps NO record of what a completion handler produced -- the ruling is
 * at `MethodMap` in src/types.ts -- so this handler cannot ask tsudoi whether an
 * item is one of the example's own. It can only read what the completion module
 * WROTE ONTO THE ITEM, which is why the mark and its reader are defined THERE
 * and imported here rather than spelled out twice. Two modules agreeing about a
 * key by convention drift the first time either is edited, and nothing in an
 * editor says so: the details simply stop appearing.
 *
 * WHAT A READER SHOULD KNOW BEFORE COPYING IT, and it is a property of any
 * resolve handler rather than of this one: THE ITEM ARRIVES FROM THE CLIENT.
 * `data` is whatever the client sent back, so a mark can be forged, and this
 * handler will then `stat` a path nobody's completion chose. That is harmless
 * here -- a `stat` reveals a size and a date to the user who asked for it, on a
 * machine they are already running the server on -- and it would NOT be harmless
 * in a handler that opened the file, ran a command, or answered with its
 * contents. Nothing is validated below, deliberately: a check would suggest this
 * boundary can be closed, and it cannot be. What decides it is what the handler
 * DOES with the path.
 */
// `Stats` is declared by node:fs and only the promise-shaped `stat` by
// node:fs/promises, so the two lines are the runtimes' shape rather than a
// preference -- measured, TS2724 names it.
import type { Stats } from "node:fs";
import { stat } from "node:fs/promises";
import type { MethodHandler } from "@atusy/tsudoi-language-server/types";
import { completedPath } from "./completion-path.ts";

/**
 * What one line of `detail` says about a path.
 *
 * `detail` AND NOT `documentation`, and it is the counterpart of that module's
 * opposite choice: the documentation is a multi-line block with a rule in it,
 * while this is one line a client can show inline beside the label -- which is
 * where a size and a date want to be read.
 *
 * NO SIZE FOR A DIRECTORY, which is a decision rather than an omission. A
 * directory's `size` is the size of its directory ENTRY -- 64 units on one
 * filesystem and 4096 on the next for the same two children -- so it is the
 * filesystem's business and says nothing about what is inside. Showing it would
 * put a number in front of a user that invites exactly the wrong reading.
 *
 * MTIME AS ISO 8601 IN UTC, because this string is generated by a server and
 * read by a person who may be anywhere: a locale-formatted date would be
 * formatted for the machine the server happens to run on.
 */
function detailFor(stats: Stats): string {
  const modified = `modified ${stats.mtime.toISOString()}`;
  return stats.isDirectory()
    ? `directory · ${modified}`
    : `file · ${String(stats.size)} bytes · ${modified}`;
}

/**
 * A `completionItem/resolve` handler that fills in a path item's file detail.
 *
 * THE ITEM COMES BACK UNCHANGED IN TWO CASES, and neither is an error path.
 *
 * AN ITEM THIS EXAMPLE DID NOT PRODUCE carries no mark, and the protocol's
 * answer REPLACES the item in the client's list -- so anything other than the
 * item itself DROPS THE ENTRY THE USER IS LOOKING AT. src/types.ts rules it, and
 * a client may legitimately send one: resolve asks about an item the client
 * holds, not about one tsudoi remembers.
 *
 * A PATH THAT IS GONE by the time the user highlights the item is ordinary
 * rather than exceptional -- a popup outlives a `git checkout` in another window
 * -- so the rejection is swallowed for the reason an unlistable directory
 * contributes nothing to completion instead of failing it: an escaped rejection
 * is answered -32603 and takes away the popup the user is reading. Nothing is
 * written to stderr either, or every stale item a user scrolls past would put a
 * line in the editor's log.
 *
 * A COPY RATHER THAN A MUTATION, because the item is the request's params and a
 * handler that edits them in place is writing into somebody else's object.
 */
export const resolvePathStat: MethodHandler<"completionItem/resolve"> = async (_context, item) => {
  const path = completedPath(item);
  if (path === undefined) {
    return item;
  }
  try {
    return { ...item, detail: detailFor(await stat(path)) };
  } catch {
    return item;
  }
};
